# Generated by Django 5.0 on 2023-12-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('channel', models.CharField(max_length=50)),
                ('medium', models.CharField(max_length=50)),
                ('campaign', models.CharField(max_length=50)),
                ('keyword', models.CharField(max_length=50)),
                ('ad_content', models.CharField(max_length=50)),
                ('ad_group', models.CharField(max_length=50)),
                ('landing_page', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('orders', models.CharField(max_length=50)),
            ],
        ),
    ]
